package:
  name: umis
  version: '1.0.5'

build:
  number: 0

source:
  url: https://github.com/vals/umis/archive/v1.0.5.tar.gz
  sha256: 107903c8bf1ebf8be3ca1b83ef641ef7c3764fd1e7d752aa69be886d8ba39ce0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython
  run:
    - python
    - pandas
    - "click>=7.0"
    - pysam
    - regex
    - toolz
    - scipy
test:
  commands:
    - LC_ALL="en_US.utf8" umis version

about:
  home: https://github.com/vals/umis
  license: MIT
  summary: Tools for processing UMI RNA-tag data

extra:
  container:
    # click requires a unicode locale when used with Python 3
    # extended-base generates en_US.UTF-8 locale and sets LC_ALL, LANG properly
    extended-base: true  # [py3k]
